body = [*(link / form / representation / directive)]

link = [link: 2, relation, target, ?body]

relation = text / int

target = iri / literal / null

literal = bool / int / float / bytes / text

form = [form: 3, relation, method, iri, ?form-data]

form /= [form.create: 4, ?accept: uint .size 2]

form /= [form.update: 5, ?accept: uint .size 2]

form /= [form.delete: 6]

form /= [form.search: 7, ?accept: uint .size 2]

method = text / uint

form-data = [*(form-field-name, form-field-value)]

form-field-name = text / uint

form-field-value = iri / bool / int / float / bytes / text / null

representation = [representation: 0, text / uint, bytes]

directive = base-directive

base-directive = [base: 1, iri]

iri = [?(scheme:    1, text),
       ?(host.name: 2, text //
         host.ip:   3, bytes .size 4 / bytes .size 16),
       ?(port:      4, uint .size 2),
       ?(path.type: 5, path-type),
       *(path:      6, text),
       *(query:     7, text),
       ?(fragment:  8, text)]

path-type = &(absolute-path:   0,
              append-path:     1,
              relative-path:   2,
              append-relation: 3)
